### ISSUE TITLE
The mod doesn't work

### ISSUE THREAD

**Issue by sebasespana** [pollend/Parkitect_Track_Modify#12]
Hello,  4 days ago steam or the game updated and then I couldn't make modifications to the roller coasters, the white dots apear but I can't move the rails to any direction.

I attached a video about the error and the error txt
https://youtu.be/Ta3xrk_ZAyo
[Issue.txt](https://github.com/parkitect-mod-community/TrackEdit/files/4944789/Issue.txt)

**Comment by pollend** [comment]
I released an update. hopefully it should be working again.
